// ALERT
export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
// SIGNUP ACTIONS
export const SIGNUP_BEGIN = 'SIGNUP_BEGIN';
export const SIGNUP_COMPLETE = 'SIGNUP_COMPLETE';
export const SIGNUP_ERROR= 'SIGNUP_ERROR';