// ALERT
export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
// AUTH ACTIONS
export const AUTH_BEGIN = 'AUTH_BEGIN';
export const AUTH_COMPLETE = 'AUTH_COMPLETE';
export const AUTH_ERROR= 'AUTH_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
// TOGGLE ACTIONS
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
// UPDATE USER ACTIONS
export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_COMPLETE = 'UPDATE_USER_COMPLETE';
export const UPDATE_USER_ERROR= 'UPDATE_USER_ERROR';